variants:
  - symbol: GBPJPY
    csv: "data/GBPJPY_H1.csv"
    balance: 10000
    pip_value: 10
    max_lot: 1.0
    pip_size: 0.01
    sl_buffer_pips: 5
    fvg_min_gap: 2
    lookback_bars: 150
    volume_filter: true
    session_time_filter: true
    htf: 60
    ctf: 5
    session: "Tokyo"

  - symbol: EURUSD
    csv: "data/EURUSD_H1.csv"
    balance: 10000
    pip_value: 10
    max_lot: 1.0
    pip_size: 0.0001
    sl_buffer_pips: 5
    fvg_min_gap: 2
    lookback_bars: 150
    volume_filter: true
    session_time_filter: true
    htf: 240
    ctf: 15
    session: "London"

walk_forward:
  lookback: 1000
  horizon: 250
  top_n: 1
