# === Trading Parameters ===
timeframe: M5             # Aggregated timeframe used by TimeframeAggregator
lookback_bars: 100        # Number of bars to look back when feeding strategy

poll_interval: 10         # Seconds between each process_tick loop

# === Risk Management ===
risk:
  risk_per_trade: 0.01     # Fraction of balance to risk per trade
  max_lot: 1.0             # Max lot size per trade
  min_lot: 0.01            # Minimum allowed lot size

# === Portfolio Constraints ===
portfolio:
  total_budget: 100000     # Total budget for all symbols
  max_exposure_per_symbol: 0.3  # Max 30% of portfolio on any one symbol

# === Trailing Stop Settings ===
trailing_stop:
  enabled: true
  trigger_pips: 15         # When in profit by 15 pips, start trailing
  trail_pips: 10           # Maintain 10 pips distance as price moves

# === Pip Values per Symbol ===
pip_values:
  EURUSD: 0.0001
  GBPUSD: 0.0001
  USDJPY: 0.01
  BTCUSD: 1.0
  XAUUSD: 0.1

# === Schedule Configuration ===
schedule_config:
  rebalance:
    enabled: true
    frequency: weekly         # Options: daily, weekly
    time: "01:00"             # UTC time to run rebalancing
    day_of_week: "sun"        # Required for weekly frequency

  performance_log:
    enabled: true
    frequency: daily
    time: "23:55"

# === Strategy Settings (Optional block used by DRLFusionStrategy) ===
strategy:
  confidence_threshold: 0.7    # Probability threshold to trigger trade
  sl_multiplier: 1.5           # ATR multiplier for stop loss
  rr_ratio: 2.0                # Risk-to-reward ratio for take profit
  use_soft_voting: true        # Whether to use ensemble of agents
  enable_partial_close: true   # Allow partial take profits
  max_open_trades: 3           # Cap concurrent trades per symbol
